deploy:
  provider: npm
  email: technique@yocto.re
  api_key:
    secure: stuabAq31T71Jd/AvFDoBLYpxHs84CB25CEfrNurGndWyn7ucnH60uaj7Qog2KQtirvbdi/3LqvzqlyolQNI8nT11muhbfbckEEMVV8Gu1vhdND3NCJUxqo8OlpeRm9NcGiFpd6J70X+HKxDFqTnC4F9uIAx71wBEFNBtsgYsFvdMtWLdT+Tr0oFdTaFbYg7486IcUQwMZxsBBWXEYiO0aosYzFB19ztYBbbHy5XGX9Da0f7zwlUEIVjtHLHo+1xLcdKsU+vOGLvI6DM6zVIPGHrg0WKd55Q3r6AOCeM83JP59A8fFQFBfpDawSD2TQWxQDMY43sHDLjILTSJXSmoqLG4FolGu/uRGy7AHEZqXBQesnE59mX+MTQvDKajWohCVU2KgVFyooPwAbhLo61TMfOeiQHJcdmSF+v2KcNMK5qeZa0C+ervI1MVrqSdwoZ9RTnB9AKTfQKCF2qbb102Wv+iCkdzci2nsaJpE1WK6dfzzuBVh1dpiOhGAzQopZ300U3/MKfvGXdsHKbRil46IOHEySs77SlrDuLkqbFO5lJ7uSrv6fqNp4PQloDyzlu8L66Ph0EJDAiFKbWGzn/HX7r7o18T2rWxBFGD0gY60WDB2W0OiquMWn2rsFOr12iFiYxk1UBMyFucxSz+SVpjXINuvW84nRI/cUkLovI0fA=
  on:
    tags: true
    repo: yoctore/yocto-sftp
